name: Test V2 Demo

on:
  push:
    branches:
      - main
      - work
  pull_request:
    branches:
      - main

jobs:
  test-demos:
    name: Test demos on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - "12"
          - "14"
          - "16"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # use node 16 to build project here
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      # test with specific node version
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Webpack build test
        run: |
          pnpm run -r demo:webpack-build

      - name: Vite build test
        run: |
          pnpm run -r run demo:vite-build

  linter-and-unit:
    name: Linter and Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Linter test
        run: |
          pnpm run lint:check
          pnpm run lint:md

      - name: Unit test
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run test

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
